name: marketo-monkey
version: 0.4
summary: CLI tool to facilitate Marketo integration
description: |
  CLI tool to facilitate Marketo integration
icon: marketo-monkey.png
confinement: strict
grade: stable

apps:
  marketo-monkey:
    command: usr/bin/python3 -u $SNAP/bin/marketo-monkey.py
    plugs: [network-bind, network]

parts:
  marketo-monkey:
    plugin: python
    source: .
    python-packages:
      - python-editor
      - PyYAML
      - requests
      - termcolor
      - colorama
    prime:
      - -install
